server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://streamcal-backend.delightfultree-3548bb79.northeurope.azurecontainerapps.io/api/;
        proxy_http_version 1.1;
        proxy_ssl_verify off;
        proxy_ssl_server_name on;
        proxy_set_header Host streamcal-backend.delightfultree-3548bb79.northeurope.azurecontainerapps.io;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }
}
